services:
  backend:
    build: ./byteforge
    ports:
      - "8080:8080"


  frontend:
    security_opt:
      - label:disable
    build: ./react-app
    depends_on:
      - backend
    ports:
      - "5173:5173"
