services:
  backend:
    build: ./byteforge
    ports:
      - "8080:8080"


  frontend:
    build: ./react-app
    depends_on:
      - backend
    ports:
      - "3000:3000"
    command: npm run dev
